---

- name: Using Azure collection
  hosts: localhost
  collections:
    - azure.azcollection
  tasks:
    - azure_rm_storageaccount:
        resource_group: chongdatasystem-datalake
        name: mystorageaccount
        account_type: Standard_LRS