---

- name: Create a user user_kafka on all machines
  hosts: all
  #vars:
    #user_name: xxx
    #user_state: present  
  #vars_files:
    #- vars/users.xml
  remote_user: achong
  #become: true
  tasks:
  # We can referenciate variable {{ user_name }}
    - name: Create user (user-kafka) with uui 4000 if no exists
      #debug:
        #msg: "teste debug"
      #no_log: true #------------ supress output value
      user:
        name: user_kafka  # {{ user_name }}
        password: 1qaz2wsX
        uid: 4000
        state: present #absent


