---

- name: Create a users and groups on all machines
  hosts: all
  remote_user: achong
  #become: true
  tasks:
    - name: Create groups
      group:
        name: "{{ item }}"
      loop:
        - kafkadeveloper 
        - connectordeveloper

    - name: Create user in their groups
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
      with_dict:
        - { name: 'luis', groups: 'kafkadeveloper'} 
        - { name: 'joao', groups: 'kafkadeveloper'} 
        - { name: 'chico', groups: 'connectordeveloper'} 
  
  


