# stop all kafka vm machines
name: Stop all kafka vm machines

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but based on branchs
  push:
    branches: ["Feature/Workflow_Stop_all_vm"]
  
  pull_request:
    #types: [closed]
    branches: [ "Feature/Workflow_Stop_all_vm"]

  pull_request_review:
    types: [submitted]
    branches: [ "Feature/Workflow_Stop_all_vm"]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a jobs 
    Initial-Steps:
      name: Initial-Steps
      
      # The type of runner that the job will run on
      runs-on: 
        - self-hosted #ubuntu-latest
        - ansible-vm-runner

      if: github.event.review.state == 'approved'

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3

        - name: Publish ansible Playbooks to an Artifact
          uses: actions/upload-artifact@v3
          with:
            name: playbooks
            path: ansible
     
    Stop-Vm:  
      name: Stop-Vm
      needs: Initial-Steps

      # The type of runner that the job will run on
      runs-on: 
        - self-hosted #ubuntu-latest
        - ansible-vm-runner

      if: github.event.review.state == 'approved'

      steps:  
        - uses: actions/download-artifact@v3
          with:
            name: playbooks
            path: ansible
      
        # stop vms machines on azure   
        - name: Run ansible script to stop vms machines on azure
          shell: bash 
          run: 
            ansible-playbook -i ansible/inventory-dev.yml ansible/AZURE/AZURE_RM_MODULES/VM/playbook_stop_all_kafka_machines.yml

        
        # We can use another option to run playbooks
        # https://github.com/dawidd6/action-ansible-playbook
        #- uses: dawidd6/action-ansible-playbook@v2
          #with:
            #playbook: playbook.yml
            #directory: ansible
            #options: |
              #--inventory inventory-test.yml
              #--extra-vars "test_ssh_password=${{ Secrets.TEST_SSH_PASSWORD }}"

      